# Generated by Django 4.2.7 on 2025-11-15 09:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resultcomponent_linked_quiz_questionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_a',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_b',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_c',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_d',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
