# Generated by Django 4.2.7 on 2025-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_question_option_a_alter_question_option_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('objective', 'Objective'), ('multichoice', 'Multi-Choice'), ('theory', 'Theory')], default='objective', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
