# Generated by Django 4.2.7 on 2025-11-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_address', models.TextField()),
                ('school_logo', models.ImageField(blank=True, upload_to='school/')),
                ('school_seal', models.ImageField(blank=True, upload_to='school/')),
                ('principal_signature', models.ImageField(blank=True, upload_to='school/')),
                ('principal_name', models.CharField(max_length=100)),
                ('proprietor_name', models.CharField(blank=True, max_length=100)),
                ('school_motto', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.ImageField(blank=True, upload_to='students/'),
        ),
        migrations.AddField(
            model_name='term',
            name='result_published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ResultToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True)),
                ('max_uses', models.IntegerField(default=3)),
                ('uses_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_comment', models.TextField(blank=True)),
                ('proprietor_comment', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('total_days', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
