# Generated by Django 4.2.7 on 2025-11-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schoolsettings_student_passport_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychomotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_games', models.CharField(blank=True, max_length=5)),
                ('handwriting', models.CharField(blank=True, max_length=5)),
                ('drawing_painting', models.CharField(blank=True, max_length=5)),
                ('crafts', models.CharField(blank=True, max_length=5)),
                ('music_drama', models.CharField(blank=True, max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'verbose_name': 'Psychomotor',
                'verbose_name_plural': 'Psychomotor',
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='EffectiveDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.CharField(blank=True, max_length=5)),
                ('neatness', models.CharField(blank=True, max_length=5)),
                ('attentiveness', models.CharField(blank=True, max_length=5)),
                ('politeness', models.CharField(blank=True, max_length=5)),
                ('relationship_with_others', models.CharField(blank=True, max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'verbose_name': 'Effective Domain',
                'verbose_name_plural': 'Effective Domains',
                'unique_together': {('student', 'term')},
            },
        ),
    ]
