# Generated by Django 4.2.7 on 2025-12-04 18:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_psychomotor_effectivedomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('objective', 'Objective (SCQ)'), ('multichoice', 'Multi-Choice (MCQ)'), ('theory', 'Theory')], default='objective', max_length=20),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_a',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_b',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_c',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_d',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
