# Generated by Django 4.2.7 on 2026-02-01 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_book_bookcategory_digitalresource_bookborrowing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('payment', 'Payment'), ('bulk_operation', 'Bulk Operation')], max_length=20)),
                ('model_name', models.CharField(choices=[('fee_structure', 'Fee Structure'), ('student_fee', 'Student Fee'), ('fee_payment', 'Fee Payment'), ('scholarship', 'Scholarship'), ('scholarship_recipient', 'Scholarship Recipient'), ('staff_payroll', 'Staff Payroll'), ('financial_transaction', 'Financial Transaction'), ('payroll_structure', 'Payroll Structure')], max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='core_financ_model_n_4132e8_idx'), models.Index(fields=['user', 'timestamp'], name='core_financ_user_id_c05e42_idx'), models.Index(fields=['operation', 'timestamp'], name='core_financ_operati_fd9b03_idx')],
            },
        ),
    ]
