# Generated by Django 4.2.7 on 2026-02-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_bookborrowing_borrower_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('subject_teacher', 'Subject Teacher'), ('class_teacher', 'Class Teacher'), ('librarian', 'Librarian'), ('super_admin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
