# Generated by Django 4.2.7 on 2026-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('subject_teacher', 'Subject Teacher'), ('class_teacher', 'Class Teacher'), ('librarian', 'Librarian'), ('accountant', 'Accountant'), ('super_admin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
